### ISSUE TITLE
Addon is vulnerable to XSS / incorrectly rendering data

### ISSUE THREAD

**Issue by nint8835** [patrick91/astro-meta-tags#2]
# Description

Currently, this library uses string templating to include user-provided data without any escaping, which leaves it open to XSS. As this is only accessible locally the risk is pretty low, but this also causes potentially valid meta tags to render incorrectly in the UI.

# Reproduction

Create an astro file containing the following content:

```html
<html>
    <head>
        <meta name="description" content="<img src='https://picsum.photos/200' />" />
    </head>
</html>
```

Open the page & open the meta tags toolbar window. You should see the description field having an `img` tag injected into it.

![image](https://github.com/patrick91/astro-meta-tags/assets/1741548/9c9ead71-c7fb-4950-bbb9-01ffbedea321)

**Comment by patrick91** [comment]
@nint8835 thanks for the report, I think the risk is low too, but it's always good to make it better 😊

do you want to do a PR? otherwise I can take a look at it 😊

**Comment by nint8835** [comment]
I'm up for doing a PR - I started doing it but figured it'd be better to get your input on it first rather than appearing out of the blue with a non-trivial PR. I can either add a dependency on something like dompurify to sanitize the user input, or rewrite the code to use document.createElement instead of template strings - you have a preference?

**Comment by patrick91** [comment]
@nint8835 let's go with `document.createElement` for now 😊
