### ISSUE TITLE
Bug: Twitter tags use the 'name' attribute, not the 'property' attribute

### ISSUE THREAD

**Issue by tugrulates** [patrick91/astro-meta-tags#5]
Per https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary

**Comment by patrick91** [comment]
Ah interesting, I never noticed that! I'll add support for both name and property, some places use property, not sure if twitter supports both 🤔

**Comment by patrick91** [comment]
Released in 0.2.2, thanks!
