### ISSUE TITLE
Add checks for meta: name="theme-color" 

### ISSUE THREAD

**Issue by teinett** [patrick91/astro-meta-tags#8]
There is meta tag `theme-color` for color of browser tab: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

Could you add checks for this meta tag, please?

```
<meta name="theme-color" content="#4285f4" />
<meta name="theme-color" media="(prefers-color-scheme: light)" content="cyan" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="black" />
```

There should be two checks:

1) the presence of the meta-tag
2) show the color

**Comment by patrick91** [comment]
@teinett done in 0.3.0 :)
